model:
  loss_rate: 0.5  # 竞争失败者的人口损失系数

time:
  start: 2000
  end: 5000
  freq: 'Y'

farmer:
  growth_rate: 0.1  # 0.1~0.25
  min_size: 6  # 最小为6（Binford 2001； Kelly 2013）
  # 在满足一定人口数量后，每时间单位有x几率向外扩散30-60人的农业殖民队
  new_group_size: [30, 60]
  diffuse_prob: 0.05
  complexity: 1.25  # 复杂化时人口规模上限的增加系数
  affiliated: 0.5  # 复杂化时附属农民的人口上限规模

hunter:
  growth_rate: 0.04
  min_size: 6  # 最小为6（Binford 2001；Kelly 2013）
  max_size: 5024
  settle_size: 100
  intensified_coefficient: 1.5  # 狩猎采集者相对农民具有优势
  convert_rate: 0.01  # 狩猎采集者转化成农民的概率
