root: /Users/songshgeo/Documents/VSCode/SC-20230710-SCE

hydra:
  job:
    name: try_new  # 实验的名字
  run:
    dir: 'out/${hydra:job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}'  # 不要修改这个
  sweep:
    dir: out/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}  # 不要修改这个
    subdir: ${hydra:job.name}_${hydra.job.num}  # 不要修改这个

exp:
  run_id: ${hydra:job.id}  # 不要修改这个
  repeats: 1  # 每组参数的运行重复次数
  note: 运行一次，看看能不能跑出数据了。  # 实验笔记

model:
  loss_rate: 0.5  # 竞争失败者的人口损失系数

env:
# 1 亚热带常绿阔叶林类型=1042.57人/32.65百平方公里（31.93人/百平方公里）、海岸常绿阔叶林类型=2892.17人/72.72百平方公里（39.77人/百平方公里）（Binford 2001: 143）海岸地带可以参考即有考古发掘材料设置人口局限较高的地块；2 参考已有全球狩猎采集者人口上限计算结果（Tallavaara et al. 2017 及补充材料；
  lim_h: 31.93  # 如果不输入空间数据，就用这个默认值
  init_hunters: 0.05  # 初始设置5%的地块有狩猎采集者
  lam: 1  # 添加农民数量的期望
  lim_g: 30  # 一般格子的上限

time:
  end: 10

farmer:
  area: 2
  # 假定每格只能拥有一个独立的农民群体（华南史前遗址间最近距离平均值为广西9.13km，广东6.43km。排除多出现于晚期复杂社会的相邻聚落结构，早期农业人群扩散时的遗址间距只会更高，因此使用该假设Wu et al. 2023），其所能利用的耕地限定在周围2公里范围内（Shelach, 1999）
  growth_rate: 0.1  # 0.1~0.25
  min_size: 6  # 最小为6（Binford 2001； Kelly 2013）
  # 在满足一定人口数量后，每时间单位有x几率向外扩散30-60人的农业殖民队
  new_group_size: [30, 60]
  diffuse_prob: 0.05
  complexity: 0.1  # 复杂化后人口增加速率下降多少
  convert_prob: 0.08
  max_travel_distance: 5

hunter:
  init_size: [0, 35]  # 最初大小是多少，第一个数是最小值，第二个数是最大值。但注意设置最小值若小于群体能够生存的最小值的情况下，这个值也会自动变成理论最小值。即对于狩猎采集者而言，设置0的话，也会变成 min_size 的参数值 6。
  convert_prob: 0.05
  new_group_size: [6, 31]
  growth_rate: 0.04
  min_size: 6  # 最小为6（Binford 2001；Kelly 2013）
  intensified_coefficient: 1.5  # 狩猎采集者相对农民具有优势
  max_travel_distance: 5
  is_complex: 100  # 超过多少之后狩猎采集者不再移动


db:
  dem: data/hn_dem_10km1.tif
  slo: data/hn_slo_10km1.tif
  asp: data/hn_asp_10km1.tif
  farmland: data/farmland.tif
  lim_h: data/hg_popu.tif  # 修改最大的上限数据路径
