root: /Users/songshgeo/Documents/VSCode/SC-20230710-SCE

model:
  loss_rate: 0.5  # 竞争失败者的人口损失系数

env:
# 1 亚热带常绿阔叶林类型=1042.57人/32.65百平方公里（31.93人/百平方公里）、海岸常绿阔叶林类型=2892.17人/72.72百平方公里（39.77人/百平方公里）（Binford 2001: 143）海岸地带可以参考即有考古发掘材料设置人口局限较高的地块；2 参考已有全球狩猎采集者人口上限计算结果（Tallavaara et al. 2017 及补充材料；
  lim_h: 31.93

time:
  start: 2000
  end: 2100
  freq: 'Y'

farmer:
  area: 2
  # 假定每格只能拥有一个独立的农民群体（华南史前遗址间最近距离平均值为广西9.13km，广东6.43km。排除多出现于晚期复杂社会的相邻聚落结构，早期农业人群扩散时的遗址间距只会更高，因此使用该假设Wu et al. 2023），其所能利用的耕地限定在周围2公里范围内（Shelach, 1999）
  growth_rate: 0.1  # 0.1~0.25
  min_size: 6  # 最小为6（Binford 2001； Kelly 2013）
  # 在满足一定人口数量后，每时间单位有x几率向外扩散30-60人的农业殖民队
  new_group_size: [30, 60]
  diffuse_prob: 0.05
  complexity: 0.1  # 复杂化后人口增加速率下降多少
  convert_prob: 0.08
  max_travel_distance: 5

hunter:
  convert_prob: 0.05
  new_group_size: [30, 60]
  growth_rate: 0.04
  min_size: 6  # 最小为6（Binford 2001；Kelly 2013）
  max_size: 5024
  settle_size: 100
  intensified_coefficient: 1.5  # 狩猎采集者相对农民具有优势
  max_travel_distance: 5


db:
  dem: data/hn_dem_10km1.tif
  slo: data/hn_slo_10km1.tif
  asp: data/hn_asp_10km1.tif
