defaults:
  - default
  - _self_

root: /Users/songshgeo/Documents/VSCode/SC-20230710-SCE

hydra:
  searchpath:
    - pkg://abses.conf

exp:
  name: south_china_evolution
  repeats: 5  # 每组参数的运行重复次数
  num_process: 5  # 并行运算的进程数
  plot_heatmap: 'bkp_farmer'  # 绘制热图的变量

model:
  save_plots: True  # 保存绘图
  loss_rate: 0.5  # 竞争失败者的人口损失系数
  n_bkps: 1
  # 识别断点的数据是依赖于：
  # 1. 人口绝对数量：size
  # 2. 人口相对比例：ratio
  # 3. 人口群体数量：group
  # 4. 人口群体比例：group_ratio
  detect_bkp_by: 'size'

reports:
  model:
    len_farmers: "farmers group ratio"
    len_hunters: "hunters group ratio"
    len_rice: "rice group ratio"
    num_farmers: "farmers size ratio"
    num_hunters: "hunters size ratio"
    num_rice: "rice size ratio"
    len_farmers_n: "farmers group num"
    len_hunters_n: "hunters group num"
    len_rice_n: "rice group num"
    num_farmers_n: "farmers size num"
    num_hunters_n: "hunters size num"
    num_rice_n: "rice size num"
  final:
    # 断点检测
    bkp_farmer: "bkp_farmers"
    bkp_rice: "bkp_rice"
    bkp_hunters: "bkp_hunters"
    # 断点检测前的人口增长率
    pre_farmer: "pre_farmers"
    pre_rice: "pre_rice"
    pre_hunters: "pre_hunters"
    # 断点检测后的人口增长率
    post_farmer: "post_farmers"
    post_rice: "post_rice"
    post_hunters: "post_hunters"

env:
# 1 亚热带常绿阔叶林类型=1042.57人/32.65百平方公里（31.93人/百平方公里）、海岸常绿阔叶林类型=2892.17人/72.72百平方公里（39.77人/百平方公里）（Binford 2001: 143）海岸地带可以参考即有考古发掘材料设置人口局限较高的地块；2 参考已有全球狩猎采集者人口上限计算结果（Tallavaara et al. 2017 及补充材料；
  lim_h: 31.93  # 如果不输入空间数据，就用这个默认值
  init_hunters: 0.05  # 初始设置5%的地块有狩猎采集者
  lam_farmer: 1  # 添加农民数量的期望
  lam_ricefarmer: 1  # 添加水稻农民数量的期望
  lim_g: 30  # 一般格子的上限
  tick_farmer: 0
  tick_ricefarmer: 100
  width: 10
  height: 10

time:
  end: 10

farmer:
  area: 2
  # 假定每格只能拥有一个独立的农民群体（华南史前遗址间最近距离平均值为广西9.13km，广东6.43km。排除多出现于晚期复杂社会的相邻聚落结构，早期农业人群扩散时的遗址间距只会更高，因此使用该假设Wu et al. 2023），其所能利用的耕地限定在周围2公里范围内（Shelach, 1999）
  growth_rate: 0.004  # 0.1~0.25
  min_size: 6  # 最小为6（Binford 2001； Kelly 2013）
  # 在满足一定人口数量后，每时间单位有x几率向外扩散30-60人的农业殖民队
  new_group_size: [30, 60]
  diffuse_prob: 0.05
  complexity: 0.1  # 复杂化后人口增加速率下降多少
  convert_prob:
    to_hunter: 0.08
    to_rice: 0.05  # TODO: 这个是多少
  convert_threshold:
    to_hunter: 100  # 超过100人之后就不再转化成狩猎采集
    to_rice: 200  # 超过200人才可以转化成水稻农民
  max_travel_distance: 5  # 最远移动距离
  capital_area: 0.004
  loss:
    prob: 0.05
    rate: 0.1

hunter:
  init_size: [0, 35]  # 最初大小是多少，第一个数是最小值，第二个数是最大值。但注意设置最小值若小于群体能够生存的最小值的情况下，这个值也会自动变成理论最小值。即对于狩猎采集者而言，设置0的话，也会变成 min_size 的参数值 6。
  convert_prob:
    to_farmer: 0.05
    to_rice: 0.05
  new_group_size: [6, 31]
  growth_rate: 0.0008
  min_size: 6  # 最小为6（Binford 2001；Kelly 2013）
  intensified_coefficient: 1.5  # 狩猎采集者相对农民具有优势
  max_travel_distance: 5
  is_complex: 100  # 超过多少之后狩猎采集者不再移动

ricefarmer:
  area: 2
  # 假定每格只能拥有一个独立的农民群体（华南史前遗址间最近距离平均值为广西9.13km，广东6.43km。排除多出现于晚期复杂社会的相邻聚落结构，早期农业人群扩散时的遗址间距只会更高，因此使用该假设Wu et al. 2023），其所能利用的耕地限定在周围2公里范围内（Shelach, 1999）
  growth_rate: 0.005  # 0.1~0.25
  min_size: 6  # 最小为6，意味着小于这个会直接死掉，不影响小于200会转换成普通农民的逻辑
  # 在满足一定人口数量后，每时间单位有x几率向外扩散200-300人的农业殖民队
  new_group_size: [200, 300]
  diffuse_prob: 0.05
  complexity: 0.1  # 复杂化后人口增加速率下降多少
  convert_prob:
    to_farmer: 1  # 满足 threshold 就一定会转换
  convert_threshold:
    to_farmer: 200
  max_travel_distance: 5  # 最远移动距离
  capital_area: 0.002
  loss:
    prob: 0.05
    rate: 0.1


db:
  dem: data/hn_dem_10km1.tif
  slo: data/hn_slo_10km1.tif
  asp: data/hn_asp_10km1.tif
  farmland: data/farmland.tif
  lim_h: data/hg_popu.tif  # 修改最大的上限数据路径
